---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: intro-rs
spec:
  replicas: 3 # Podのレプリカ数
  selector:
    matchLabels:
      app: web
  template:   # Podのレプリカを作るためのテンプレート
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx